dist: trusty
sudo: false

language: elixir
elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.3
  - 1.6.1
otp_release:
  - 18.3
  - 19.2
  - 20.2

before_script:
  - mix local.hex --force
  - mix deps.get --only test
